### ISSUE TITLE
Pinto Fails to Find Extension Directory

### ISSUE THREAD

**Issue by bor-real** [PintoIM/Pinto#52] opened 2023-06-28 05:08 UTC
## Description
When Pinto runs, it checks for an extensions directory.  If it doesn't find it, instead of creating it, the program crashes.
As far as I know, the program never attempts to create the directory

## To Reproduce
Download Pinto on a Fresh 22H2 Windows 10 machine
#### OR
Delete Pinto Appdata Directory

## Expected behavior
Pinto opens to login screen

## How to Fix
Check for the directory and if it doesn't exist, create it.

## Screenshots
![image](https://github.com/PintoIM/Pinto/assets/90580455/082bb7fc-776e-4405-b18d-2a26a7242ebc)

## Desktop:
- OS: [Windows 10 22H2 ] 
![image](https://github.com/PintoIM/Pinto/assets/90580455/a2ed74d3-e3f0-4726-8642-e61355d6de2e)
- Pinto! Version: Beta 1.0 Prerelease 1
- ![image](https://github.com/PintoIM/Pinto/assets/90580455/bbad131c-436e-4ea1-92a0-779e3267a9b8)

## Crash Log
```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Boreal\AppData\Roaming\Pinto!\extensions'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.EnumerateFiles(String path, String searchPattern)
   at PintoNS.Program.LoadExtensions() in D:\dev\C#\Pinto\Pinto\Program.cs:line 119
   at PintoNS.Program.Main() in D:\dev\C#\Pinto\Pinto\Program.cs:line 102
```

**Comment by bor-real** [comment] 2023-06-28 05:10
This has to be my fault...
What piece of instruction did I ignore
`god`

**Comment by DexrnZacAttack** [comment] 2023-06-30 02:17
same for me

**Comment by DexrnZacAttack** [comment] 2023-06-30 02:24
for some reason it doesn't seem to mkdir the folder in appdata, idk why it even requires it to start.

**Comment by bor-real** [comment] 2023-07-01 19:27
I would assume @vlOd2 created the directory on his machine and then started working on the App Data usage implementation.

**Comment by vlOd2** [comment] 2023-07-06 20:02
Duplicate of https://github.com/PintoIM/Pinto/issues/46

**Closed by vlOd2** 2023-07-06 20:02 UTC
Labels: bug
