### ISSUE TITLE
Unable to launch Pinto Beta

### ISSUE THREAD

**Issue by RUvlad1** [PintoIM/Pinto#54] opened 2023-07-18 13:02 UTC
## Describe the bug
Upon launching the app, it immediately crashes complaining it's unable to find an extensions folder in AppData.

## To Reproduce
1. Download Pinto Beta 1.0 Pre-release 1
2. Install Pinto
3. Launch the program

## Expected behavior
Probably anything but a crash

## Screenshots
![Pinto! - Fatal Error_b1](https://github.com/PintoIM/Pinto/assets/60317461/9c6fb4ba-62fa-415a-9992-630017a248d0)

## Desktop (please complete the following information):
- OS: Windows 10 IoT Enterprise LTSC 21H2 19044.3208
- Pinto! Version: b1.0-pre1

## Additional context
No other previous versions of Pinto were installed.
The problem occurs when using either the installer or the portable version.

**Comment by RUvlad1** [comment] 2023-07-18 13:04
Should note that the issue can be fixed by manually adding the folder in Pinto's AppData folder

**Comment by vlOd2** [comment] 2023-07-18 20:15
Duplicate of https://github.com/PintoIM/Pinto/issues/46

**Closed as not planned by vlOd2** 2023-07-18 20:15 UTC
Labels: bug
