### ISSUE TITLE
i did log out and cant log back in

### ISSUE THREAD

**Issue by SonicPika** [PintoIM/Pinto#10] opened 2023-05-03 18:19 UTC
i can't login for 3 hours

![image](https://user-images.githubusercontent.com/128844731/236008016-f0a9113f-6a35-410a-a325-4ece939b8992.png)

**Comment by vlOd2** [comment] 2023-05-03 18:20
Duplicate of https://github.com/PintoIM/Pinto/issues/9

**Closed as completed by vlOd2** 2023-05-03 18:20 UTC
Labels: duplicate
